-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:5b6a976093951ae7f3a3d572fe1bb6ae$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "KernStop_1.png",
				spriteColorRect = { x = 0, y = 0, width = 61, height = 60 },
				textureRect = { x = 2, y = 2, width = 61, height = 60 },
				spriteSourceSize = { width = 61, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "KernStop_2.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 41 },
				textureRect = { x = 88, y = 107, width = 37, height = 41 },
				spriteSourceSize = { width = 37, height = 41 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "KernStop_3.png",
				spriteColorRect = { x = 0, y = 0, width = 33, height = 40 },
				textureRect = { x = 2, y = 129, width = 33, height = 40 },
				spriteSourceSize = { width = 33, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "KernStop_4.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 40 },
				textureRect = { x = 65, y = 2, width = 46, height = 40 },
				spriteSourceSize = { width = 46, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "KernStop_5.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 63 },
				textureRect = { x = 2, y = 64, width = 43, height = 63 },
				spriteSourceSize = { width = 43, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "KernStop_6.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 51 },
				textureRect = { x = 2, y = 171, width = 31, height = 51 },
				spriteSourceSize = { width = 31, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "KernStop_7.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 41 },
				textureRect = { x = 47, y = 107, width = 39, height = 41 },
				spriteSourceSize = { width = 39, height = 41 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "KernStop_8.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 61 },
				textureRect = { x = 65, y = 44, width = 44, height = 61 },
				spriteSourceSize = { width = 44, height = 61 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

