-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:9fe784716177c65bf5c29b583944ad2e$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "bracket_1.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 49 },
				textureRect = { x = 449, y = 535, width = 38, height = 49 },
				spriteSourceSize = { width = 38, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bracket_2.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 49 },
				textureRect = { x = 263, y = 223, width = 44, height = 49 },
				spriteSourceSize = { width = 44, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bracket_3.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 46 },
				textureRect = { x = 348, y = 317, width = 40, height = 46 },
				spriteSourceSize = { width = 40, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bracket_4.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 46 },
				textureRect = { x = 412, y = 218, width = 42, height = 46 },
				spriteSourceSize = { width = 42, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bracket_5.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 48 },
				textureRect = { x = 421, y = 72, width = 45, height = 48 },
				spriteSourceSize = { width = 45, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bracket_6.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 50 },
				textureRect = { x = 263, y = 452, width = 37, height = 50 },
				spriteSourceSize = { width = 37, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bracket_7.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 48 },
				textureRect = { x = 51, y = 278, width = 47, height = 48 },
				spriteSourceSize = { width = 47, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bullet_1.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 60 },
				textureRect = { x = 352, y = 255, width = 40, height = 60 },
				spriteSourceSize = { width = 40, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bullet_2.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				textureRect = { x = 305, y = 385, width = 40, height = 40 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bullet_3.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 59 },
				textureRect = { x = 240, y = 251, width = 21, height = 59 },
				spriteSourceSize = { width = 21, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bullet_5.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 41 },
				textureRect = { x = 2, y = 676, width = 32, height = 41 },
				spriteSourceSize = { width = 32, height = 41 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bullet_6.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 49 },
				textureRect = { x = 391, y = 705, width = 23, height = 49 },
				spriteSourceSize = { width = 23, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "carret_1.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 58 },
				textureRect = { x = 322, y = 134, width = 44, height = 58 },
				spriteSourceSize = { width = 44, height = 58 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "carret_2.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 41 },
				textureRect = { x = 263, y = 369, width = 40, height = 41 },
				spriteSourceSize = { width = 40, height = 41 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "carret_3.png",
				spriteColorRect = { x = 0, y = 0, width = 29, height = 40 },
				textureRect = { x = 333, y = 664, width = 29, height = 40 },
				spriteSourceSize = { width = 29, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "carret_4.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 41 },
				textureRect = { x = 341, y = 503, width = 37, height = 41 },
				spriteSourceSize = { width = 37, height = 41 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "carret_5.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 51 },
				textureRect = { x = 364, y = 698, width = 25, height = 51 },
				spriteSourceSize = { width = 25, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cicero_1.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 59 },
				textureRect = { x = 412, y = 266, width = 40, height = 59 },
				spriteSourceSize = { width = 40, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cicero_2.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 57 },
				textureRect = { x = 314, y = 113, width = 6, height = 57 },
				spriteSourceSize = { width = 6, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cicero_3.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 45 },
				textureRect = { x = 2, y = 485, width = 35, height = 45 },
				spriteSourceSize = { width = 35, height = 45 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cicero_4.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 45 },
				textureRect = { x = 39, y = 483, width = 35, height = 45 },
				spriteSourceSize = { width = 35, height = 45 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cicero_5.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 45 },
				textureRect = { x = 215, y = 566, width = 32, height = 45 },
				spriteSourceSize = { width = 32, height = 45 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cicero_6.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 45 },
				textureRect = { x = 39, y = 436, width = 35, height = 45 },
				spriteSourceSize = { width = 35, height = 45 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "comma_1.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 52 },
				textureRect = { x = 374, y = 51, width = 45, height = 52 },
				spriteSourceSize = { width = 45, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "comma_2.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 32 },
				textureRect = { x = 35, y = 761, width = 31, height = 32 },
				spriteSourceSize = { width = 31, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "comma_3.png",
				spriteColorRect = { x = 0, y = 0, width = 57, height = 32 },
				textureRect = { x = 207, y = 2, width = 57, height = 32 },
				spriteSourceSize = { width = 57, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "comma_4.png",
				spriteColorRect = { x = 0, y = 0, width = 57, height = 32 },
				textureRect = { x = 148, y = 2, width = 57, height = 32 },
				spriteSourceSize = { width = 57, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "comma_5.png",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 32 },
				textureRect = { x = 203, y = 742, width = 28, height = 32 },
				spriteSourceSize = { width = 28, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "concept_1.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 52 },
				textureRect = { x = 36, y = 707, width = 31, height = 52 },
				spriteSourceSize = { width = 31, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "concept_2.png",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 37 },
				textureRect = { x = 241, y = 726, width = 28, height = 37 },
				spriteSourceSize = { width = 28, height = 37 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "concept_3.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 37 },
				textureRect = { x = 133, y = 814, width = 27, height = 37 },
				spriteSourceSize = { width = 27, height = 37 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "concept_4.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 37 },
				textureRect = { x = 34, y = 839, width = 23, height = 37 },
				spriteSourceSize = { width = 23, height = 37 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "concept_5.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 37 },
				textureRect = { x = 168, y = 799, width = 27, height = 37 },
				spriteSourceSize = { width = 27, height = 37 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "concept_6.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 52 },
				textureRect = { x = 233, y = 765, width = 27, height = 52 },
				spriteSourceSize = { width = 27, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "concept_7.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 45 },
				textureRect = { x = 489, y = 553, width = 21, height = 45 },
				spriteSourceSize = { width = 21, height = 45 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "condensed_1.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 65 },
				textureRect = { x = 485, y = 600, width = 25, height = 65 },
				spriteSourceSize = { width = 25, height = 65 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "condensed_2.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 49 },
				textureRect = { x = 250, y = 836, width = 23, height = 49 },
				spriteSourceSize = { width = 23, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "condensed_3.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 48 },
				textureRect = { x = 353, y = 751, width = 23, height = 48 },
				spriteSourceSize = { width = 23, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "condensed_4.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 64 },
				textureRect = { x = 262, y = 770, width = 23, height = 64 },
				spriteSourceSize = { width = 23, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "condensed_5.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 49 },
				textureRect = { x = 287, y = 798, width = 23, height = 49 },
				spriteSourceSize = { width = 23, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "condensed_6.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 48 },
				textureRect = { x = 416, y = 705, width = 23, height = 48 },
				spriteSourceSize = { width = 23, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "condensed_7.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 49 },
				textureRect = { x = 327, y = 750, width = 24, height = 49 },
				spriteSourceSize = { width = 24, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "condensed_8.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 49 },
				textureRect = { x = 225, y = 819, width = 23, height = 49 },
				spriteSourceSize = { width = 23, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "condensed_9.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 64 },
				textureRect = { x = 276, y = 704, width = 23, height = 64 },
				spriteSourceSize = { width = 23, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dagger_1.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 60 },
				textureRect = { x = 197, y = 216, width = 41, height = 60 },
				spriteSourceSize = { width = 41, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dagger_2.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 41 },
				textureRect = { x = 263, y = 504, width = 37, height = 41 },
				spriteSourceSize = { width = 37, height = 41 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dagger_3.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 58 },
				textureRect = { x = 148, y = 259, width = 41, height = 58 },
				spriteSourceSize = { width = 41, height = 58 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dagger_4.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 58 },
				textureRect = { x = 148, y = 259, width = 41, height = 58 },
				spriteSourceSize = { width = 41, height = 58 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dagger_5.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 41 },
				textureRect = { x = 39, y = 576, width = 34, height = 41 },
				spriteSourceSize = { width = 34, height = 41 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dagger_6.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 40 },
				textureRect = { x = 69, y = 751, width = 31, height = 40 },
				spriteSourceSize = { width = 31, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "design_1.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 53 },
				textureRect = { x = 347, y = 407, width = 39, height = 53 },
				spriteSourceSize = { width = 39, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "design_2.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				textureRect = { x = 347, y = 365, width = 40, height = 40 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "design_3.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 40 },
				textureRect = { x = 409, y = 430, width = 39, height = 40 },
				spriteSourceSize = { width = 39, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "design_4.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 40 },
				textureRect = { x = 203, y = 776, width = 27, height = 40 },
				spriteSourceSize = { width = 27, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "design_5.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 53 },
				textureRect = { x = 409, y = 327, width = 39, height = 53 },
				spriteSourceSize = { width = 39, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "design_6.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				textureRect = { x = 190, y = 394, width = 40, height = 40 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "digital_1.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 55 },
				textureRect = { x = 148, y = 488, width = 37, height = 55 },
				spriteSourceSize = { width = 37, height = 55 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "digital_2.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 37 },
				textureRect = { x = 281, y = 665, width = 18, height = 37 },
				spriteSourceSize = { width = 18, height = 37 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "digital_3.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 55 },
				textureRect = { x = 340, y = 607, width = 36, height = 55 },
				spriteSourceSize = { width = 36, height = 55 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "digital_4.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 37 },
				textureRect = { x = 281, y = 626, width = 18, height = 37 },
				spriteSourceSize = { width = 18, height = 37 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "digital_5.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 55 },
				textureRect = { x = 187, y = 436, width = 37, height = 55 },
				spriteSourceSize = { width = 37, height = 55 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "digital_6.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 37 },
				textureRect = { x = 263, y = 547, width = 37, height = 37 },
				spriteSourceSize = { width = 37, height = 37 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "digital_7.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 55 },
				textureRect = { x = 491, y = 404, width = 18, height = 55 },
				spriteSourceSize = { width = 18, height = 55 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dynamic_1.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 47 },
				textureRect = { x = 320, y = 194, width = 44, height = 47 },
				spriteSourceSize = { width = 44, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dynamic_2.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 47 },
				textureRect = { x = 374, y = 2, width = 46, height = 47 },
				spriteSourceSize = { width = 46, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dynamic_3.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 48 },
				textureRect = { x = 2, y = 278, width = 47, height = 48 },
				spriteSourceSize = { width = 47, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dynamic_4.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 48 },
				textureRect = { x = 148, y = 148, width = 48, height = 48 },
				spriteSourceSize = { width = 48, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dynamic_5.png",
				spriteColorRect = { x = 0, y = 0, width = 73, height = 48 },
				textureRect = { x = 2, y = 2, width = 73, height = 48 },
				spriteSourceSize = { width = 73, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dynamic_6.png",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 48 },
				textureRect = { x = 59, y = 839, width = 22, height = 48 },
				spriteSourceSize = { width = 22, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dynamic_7.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 48 },
				textureRect = { x = 416, y = 122, width = 44, height = 48 },
				spriteSourceSize = { width = 44, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "font_1.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 61 },
				textureRect = { x = 450, y = 472, width = 38, height = 61 },
				spriteSourceSize = { width = 38, height = 61 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "font_2.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 46 },
				textureRect = { x = 263, y = 321, width = 40, height = 46 },
				spriteSourceSize = { width = 40, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "font_3.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 45 },
				textureRect = { x = 302, y = 481, width = 37, height = 45 },
				spriteSourceSize = { width = 37, height = 45 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "font_4.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 54 },
				textureRect = { x = 71, y = 695, width = 31, height = 54 },
				spriteSourceSize = { width = 31, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_1.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 59 },
				textureRect = { x = 370, y = 105, width = 44, height = 59 },
				spriteSourceSize = { width = 44, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_2.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 44 },
				textureRect = { x = 109, y = 642, width = 32, height = 44 },
				spriteSourceSize = { width = 32, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_3.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 44 },
				textureRect = { x = 414, y = 172, width = 44, height = 44 },
				spriteSourceSize = { width = 44, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_4.png",
				spriteColorRect = { x = 0, y = 0, width = 49, height = 44 },
				textureRect = { x = 61, y = 169, width = 49, height = 44 },
				spriteSourceSize = { width = 49, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_5.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 44 },
				textureRect = { x = 144, y = 605, width = 32, height = 44 },
				spriteSourceSize = { width = 32, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_6.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 44 },
				textureRect = { x = 180, y = 583, width = 32, height = 44 },
				spriteSourceSize = { width = 32, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_7.png",
				spriteColorRect = { x = 0, y = 0, width = 29, height = 44 },
				textureRect = { x = 68, y = 793, width = 29, height = 44 },
				spriteSourceSize = { width = 29, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_8.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 44 },
				textureRect = { x = 490, y = 507, width = 20, height = 44 },
				spriteSourceSize = { width = 20, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_9.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 44 },
				textureRect = { x = 209, y = 696, width = 30, height = 44 },
				spriteSourceSize = { width = 30, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glyph_1.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 57 },
				textureRect = { x = 447, y = 670, width = 35, height = 57 },
				spriteSourceSize = { width = 35, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glyph_2.png",
				spriteColorRect = { x = 0, y = 0, width = 10, height = 60 },
				textureRect = { x = 115, y = 116, width = 10, height = 60 },
				spriteSourceSize = { width = 10, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glyph_3.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 58 },
				textureRect = { x = 2, y = 376, width = 37, height = 58 },
				spriteSourceSize = { width = 37, height = 58 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glyph_4.png",
				spriteColorRect = { x = 0, y = 0, width = 33, height = 58 },
				textureRect = { x = 145, y = 545, width = 33, height = 58 },
				spriteSourceSize = { width = 33, height = 58 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glyph_5.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 56 },
				textureRect = { x = 106, y = 688, width = 31, height = 56 },
				spriteSourceSize = { width = 31, height = 56 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "grapheme_1.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 42 },
				textureRect = { x = 104, y = 746, width = 31, height = 42 },
				spriteSourceSize = { width = 31, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "grapheme_2.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 43 },
				textureRect = { x = 211, y = 651, width = 31, height = 43 },
				spriteSourceSize = { width = 31, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "grapheme_3.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 43 },
				textureRect = { x = 248, y = 626, width = 31, height = 43 },
				spriteSourceSize = { width = 31, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "grapheme_4.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 42 },
				textureRect = { x = 331, y = 706, width = 25, height = 42 },
				spriteSourceSize = { width = 25, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "grapheme_5.png",
				spriteColorRect = { x = 0, y = 0, width = 29, height = 42 },
				textureRect = { x = 34, y = 795, width = 29, height = 42 },
				spriteSourceSize = { width = 29, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "grapheme_6.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 42 },
				textureRect = { x = 139, y = 712, width = 31, height = 42 },
				spriteSourceSize = { width = 31, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "grapheme_7.png",
				spriteColorRect = { x = 0, y = 0, width = 59, height = 43 },
				textureRect = { x = 2, y = 52, width = 59, height = 43 },
				spriteSourceSize = { width = 59, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "grapheme_8.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 42 },
				textureRect = { x = 176, y = 690, width = 31, height = 42 },
				spriteSourceSize = { width = 31, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hyphen_1.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 59 },
				textureRect = { x = 301, y = 628, width = 30, height = 59 },
				spriteSourceSize = { width = 30, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hyphen_2.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 60 },
				textureRect = { x = 42, y = 374, width = 37, height = 60 },
				spriteSourceSize = { width = 37, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hyphen_3.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 60 },
				textureRect = { x = 409, y = 513, width = 38, height = 60 },
				spriteSourceSize = { width = 38, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hyphen_4.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 59 },
				textureRect = { x = 143, y = 651, width = 31, height = 59 },
				spriteSourceSize = { width = 31, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hyphen_5.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 45 },
				textureRect = { x = 109, y = 538, width = 34, height = 45 },
				spriteSourceSize = { width = 34, height = 45 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hyphen_6.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 44 },
				textureRect = { x = 2, y = 719, width = 31, height = 44 },
				spriteSourceSize = { width = 31, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_1.png",
				spriteColorRect = { x = 0, y = 0, width = 10, height = 56 },
				textureRect = { x = 252, y = 97, width = 10, height = 56 },
				spriteSourceSize = { width = 10, height = 56 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_2.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 46 },
				textureRect = { x = 462, y = 139, width = 44, height = 46 },
				spriteSourceSize = { width = 44, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_3.png",
				spriteColorRect = { x = 0, y = 0, width = 10, height = 46 },
				textureRect = { x = 251, y = 203, width = 10, height = 46 },
				spriteSourceSize = { width = 10, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_4.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 46 },
				textureRect = { x = 456, y = 246, width = 41, height = 46 },
				spriteSourceSize = { width = 41, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_5.png",
				spriteColorRect = { x = 0, y = 0, width = 10, height = 46 },
				textureRect = { x = 251, y = 155, width = 10, height = 46 },
				spriteSourceSize = { width = 10, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_6.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 47 },
				textureRect = { x = 368, y = 166, width = 44, height = 47 },
				spriteSourceSize = { width = 44, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_7.png",
				spriteColorRect = { x = 0, y = 0, width = 29, height = 46 },
				textureRect = { x = 102, y = 790, width = 29, height = 46 },
				spriteSourceSize = { width = 29, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "italic_1.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 59 },
				textureRect = { x = 302, y = 567, width = 36, height = 59 },
				spriteSourceSize = { width = 36, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "italic_2.png",
				spriteColorRect = { x = 0, y = 0, width = 29, height = 56 },
				textureRect = { x = 137, y = 756, width = 29, height = 56 },
				spriteSourceSize = { width = 29, height = 56 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "italic_3.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 46 },
				textureRect = { x = 148, y = 319, width = 41, height = 46 },
				spriteSourceSize = { width = 41, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "italic_4.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 59 },
				textureRect = { x = 178, y = 629, width = 31, height = 59 },
				spriteSourceSize = { width = 31, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "italic_5.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 58 },
				textureRect = { x = 129, y = 54, width = 17, height = 58 },
				spriteSourceSize = { width = 17, height = 58 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "italic_6.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 45 },
				textureRect = { x = 263, y = 274, width = 41, height = 45 },
				spriteSourceSize = { width = 41, height = 45 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mark_1.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 61 },
				textureRect = { x = 2, y = 97, width = 58, height = 61 },
				spriteSourceSize = { width = 58, height = 61 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mark_2.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 57 },
				textureRect = { x = 148, y = 429, width = 37, height = 57 },
				spriteSourceSize = { width = 37, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mark_3.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 61 },
				textureRect = { x = 109, y = 369, width = 37, height = 61 },
				spriteSourceSize = { width = 37, height = 61 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mark_4.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 61 },
				textureRect = { x = 226, y = 442, width = 35, height = 61 },
				spriteSourceSize = { width = 35, height = 61 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "micro_1.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 55 },
				textureRect = { x = 148, y = 36, width = 54, height = 55 },
				spriteSourceSize = { width = 54, height = 55 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "micro_2.png",
				spriteColorRect = { x = 0, y = 0, width = 2, height = 48 },
				textureRect = { x = 198, y = 148, width = 2, height = 48 },
				spriteSourceSize = { width = 2, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "micro_3.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 51 },
				textureRect = { x = 202, y = 97, width = 48, height = 51 },
				spriteSourceSize = { width = 48, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "micro_4.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 48 },
				textureRect = { x = 75, y = 601, width = 32, height = 48 },
				spriteSourceSize = { width = 32, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "micro_5.png",
				spriteColorRect = { x = 0, y = 0, width = 51, height = 51 },
				textureRect = { x = 62, y = 116, width = 51, height = 51 },
				spriteSourceSize = { width = 51, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mono_1.png",
				spriteColorRect = { x = 0, y = 0, width = 69, height = 50 },
				textureRect = { x = 77, y = 2, width = 69, height = 50 },
				spriteSourceSize = { width = 69, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mono_2.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 38 },
				textureRect = { x = 454, y = 294, width = 40, height = 38 },
				spriteSourceSize = { width = 40, height = 38 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mono_3.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 38 },
				textureRect = { x = 366, y = 215, width = 44, height = 38 },
				spriteSourceSize = { width = 44, height = 38 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mono_4.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 38 },
				textureRect = { x = 263, y = 412, width = 40, height = 38 },
				spriteSourceSize = { width = 40, height = 38 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "page_1.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 63 },
				textureRect = { x = 191, y = 329, width = 40, height = 63 },
				spriteSourceSize = { width = 40, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "page_2.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 46 },
				textureRect = { x = 306, y = 290, width = 40, height = 46 },
				spriteSourceSize = { width = 40, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "page_3.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 66 },
				textureRect = { x = 324, y = 66, width = 44, height = 66 },
				spriteSourceSize = { width = 44, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "page_4.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 46 },
				textureRect = { x = 109, y = 490, width = 34, height = 46 },
				spriteSourceSize = { width = 34, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pica_1.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 44 },
				textureRect = { x = 42, y = 328, width = 38, height = 44 },
				spriteSourceSize = { width = 38, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pica_2.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 50 },
				textureRect = { x = 394, y = 255, width = 16, height = 50 },
				spriteSourceSize = { width = 16, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pica_3.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 36 },
				textureRect = { x = 214, y = 613, width = 32, height = 36 },
				spriteSourceSize = { width = 32, height = 36 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pica_4.png",
				spriteColorRect = { x = 0, y = 0, width = 33, height = 36 },
				textureRect = { x = 180, y = 545, width = 33, height = 36 },
				spriteSourceSize = { width = 33, height = 36 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pitch_1.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 59 },
				textureRect = { x = 341, y = 546, width = 36, height = 59 },
				spriteSourceSize = { width = 36, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pitch_2.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 59 },
				textureRect = { x = 226, y = 505, width = 35, height = 59 },
				spriteSourceSize = { width = 35, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pitch_3.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 47 },
				textureRect = { x = 2, y = 436, width = 35, height = 47 },
				spriteSourceSize = { width = 35, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pitch_4.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 42 },
				textureRect = { x = 409, y = 621, width = 36, height = 42 },
				spriteSourceSize = { width = 36, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pitch_5.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 59 },
				textureRect = { x = 110, y = 239, width = 36, height = 59 },
				spriteSourceSize = { width = 36, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playful_1.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 53 },
				textureRect = { x = 148, y = 93, width = 52, height = 53 },
				spriteSourceSize = { width = 52, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playful_2.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 44 },
				textureRect = { x = 409, y = 575, width = 36, height = 44 },
				spriteSourceSize = { width = 36, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playful_3.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 49 },
				textureRect = { x = 191, y = 278, width = 41, height = 49 },
				spriteSourceSize = { width = 41, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playful_4.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 45 },
				textureRect = { x = 305, y = 338, width = 40, height = 45 },
				spriteSourceSize = { width = 40, height = 45 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playful_5.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 42 },
				textureRect = { x = 37, y = 663, width = 32, height = 42 },
				spriteSourceSize = { width = 32, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playful_6.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 46 },
				textureRect = { x = 409, y = 382, width = 39, height = 46 },
				spriteSourceSize = { width = 39, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playful_7.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 44 },
				textureRect = { x = 39, y = 530, width = 35, height = 44 },
				spriteSourceSize = { width = 35, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "point_1.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 62 },
				textureRect = { x = 324, y = 2, width = 48, height = 62 },
				spriteSourceSize = { width = 48, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "point_2.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 50 },
				textureRect = { x = 264, y = 110, width = 48, height = 50 },
				spriteSourceSize = { width = 48, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "point_3.png",
				spriteColorRect = { x = 0, y = 0, width = 13, height = 62 },
				textureRect = { x = 394, y = 307, width = 13, height = 62 },
				spriteSourceSize = { width = 13, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "point_4.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 48 },
				textureRect = { x = 468, y = 89, width = 42, height = 48 },
				spriteSourceSize = { width = 42, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "point_5.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 60 },
				textureRect = { x = 81, y = 415, width = 26, height = 60 },
				spriteSourceSize = { width = 26, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_1.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 51 },
				textureRect = { x = 450, y = 334, width = 39, height = 51 },
				spriteSourceSize = { width = 39, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_2.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 38 },
				textureRect = { x = 409, y = 665, width = 36, height = 38 },
				spriteSourceSize = { width = 36, height = 38 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_3.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 50 },
				textureRect = { x = 187, y = 493, width = 37, height = 50 },
				spriteSourceSize = { width = 37, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_4.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 38 },
				textureRect = { x = 447, y = 630, width = 36, height = 38 },
				spriteSourceSize = { width = 36, height = 38 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_5.png",
				spriteColorRect = { x = 0, y = 0, width = 9, height = 53 },
				textureRect = { x = 309, y = 172, width = 9, height = 53 },
				spriteSourceSize = { width = 9, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_6.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 38 },
				textureRect = { x = 249, y = 586, width = 32, height = 38 },
				spriteSourceSize = { width = 32, height = 38 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_7.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 38 },
				textureRect = { x = 215, y = 870, width = 23, height = 38 },
				spriteSourceSize = { width = 23, height = 38 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rubric_1.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 60 },
				textureRect = { x = 485, y = 667, width = 25, height = 60 },
				spriteSourceSize = { width = 25, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rubric_2.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 44 },
				textureRect = { x = 162, y = 838, width = 26, height = 44 },
				spriteSourceSize = { width = 26, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rubric_3.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 64 },
				textureRect = { x = 234, y = 312, width = 27, height = 64 },
				spriteSourceSize = { width = 27, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rubric_4.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 44 },
				textureRect = { x = 491, y = 461, width = 18, height = 44 },
				spriteSourceSize = { width = 18, height = 44 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rubric_5.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 61 },
				textureRect = { x = 316, y = 50, width = 6, height = 61 },
				spriteSourceSize = { width = 6, height = 61 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rubric_6.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 45 },
				textureRect = { x = 190, y = 870, width = 23, height = 45 },
				spriteSourceSize = { width = 23, height = 45 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sans_1.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 52 },
				textureRect = { x = 305, y = 427, width = 39, height = 52 },
				spriteSourceSize = { width = 39, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sans_2.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 39 },
				textureRect = { x = 409, y = 472, width = 39, height = 39 },
				spriteSourceSize = { width = 39, height = 39 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sans_3.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 39 },
				textureRect = { x = 450, y = 431, width = 39, height = 39 },
				spriteSourceSize = { width = 39, height = 39 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sans_4.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 39 },
				textureRect = { x = 346, y = 462, width = 39, height = 39 },
				spriteSourceSize = { width = 39, height = 39 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sketch_1.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 85 },
				textureRect = { x = 469, y = 2, width = 41, height = 85 },
				spriteSourceSize = { width = 41, height = 85 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sketch_2.png",
				spriteColorRect = { x = 0, y = 0, width = 29, height = 85 },
				textureRect = { x = 378, y = 611, width = 29, height = 85 },
				spriteSourceSize = { width = 29, height = 85 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sketch_3.png",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 35 },
				textureRect = { x = 50, y = 889, width = 22, height = 35 },
				spriteSourceSize = { width = 22, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sketch_4.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 85 },
				textureRect = { x = 82, y = 328, width = 25, height = 85 },
				spriteSourceSize = { width = 25, height = 85 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sketch_5.png",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 35 },
				textureRect = { x = 26, y = 878, width = 22, height = 35 },
				spriteSourceSize = { width = 22, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sketch_6.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 85 },
				textureRect = { x = 2, y = 765, width = 30, height = 85 },
				spriteSourceSize = { width = 30, height = 85 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slab_1.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 58 },
				textureRect = { x = 301, y = 738, width = 24, height = 58 },
				spriteSourceSize = { width = 24, height = 58 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slab_2.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 59 },
				textureRect = { x = 389, y = 371, width = 18, height = 59 },
				spriteSourceSize = { width = 18, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slab_3.png",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 47 },
				textureRect = { x = 301, y = 689, width = 28, height = 47 },
				spriteSourceSize = { width = 28, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slab_4.png",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 62 },
				textureRect = { x = 233, y = 378, width = 28, height = 62 },
				spriteSourceSize = { width = 28, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slash_1.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 67 },
				textureRect = { x = 109, y = 300, width = 37, height = 67 },
				spriteSourceSize = { width = 37, height = 67 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slash_2.png",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 68 },
				textureRect = { x = 2, y = 928, width = 22, height = 68 },
				spriteSourceSize = { width = 22, height = 68 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slash_3.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 42 },
				textureRect = { x = 447, y = 586, width = 36, height = 42 },
				spriteSourceSize = { width = 36, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slash_4.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 42 },
				textureRect = { x = 127, y = 853, width = 26, height = 42 },
				spriteSourceSize = { width = 26, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slash_5.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 68 },
				textureRect = { x = 422, y = 2, width = 45, height = 68 },
				spriteSourceSize = { width = 45, height = 68 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sort_1.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 59 },
				textureRect = { x = 76, y = 540, width = 31, height = 59 },
				spriteSourceSize = { width = 31, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sort_2.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 43 },
				textureRect = { x = 2, y = 532, width = 35, height = 43 },
				spriteSourceSize = { width = 35, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sort_3.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 42 },
				textureRect = { x = 155, y = 884, width = 23, height = 42 },
				spriteSourceSize = { width = 23, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sort_4.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 53 },
				textureRect = { x = 99, y = 838, width = 26, height = 53 },
				spriteSourceSize = { width = 26, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "space_1.png",
				spriteColorRect = { x = 0, y = 0, width = 33, height = 55 },
				textureRect = { x = 109, y = 585, width = 33, height = 55 },
				spriteSourceSize = { width = 33, height = 55 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "space_2.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 60 },
				textureRect = { x = 148, y = 367, width = 40, height = 60 },
				spriteSourceSize = { width = 40, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "space_3.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 42 },
				textureRect = { x = 450, y = 387, width = 39, height = 42 },
				spriteSourceSize = { width = 39, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "space_4.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 42 },
				textureRect = { x = 72, y = 651, width = 32, height = 42 },
				spriteSourceSize = { width = 32, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "space_5.png",
				spriteColorRect = { x = 0, y = 0, width = 33, height = 42 },
				textureRect = { x = 37, y = 619, width = 33, height = 42 },
				spriteSourceSize = { width = 33, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "spacing_1.png",
				spriteColorRect = { x = 0, y = 0, width = 33, height = 58 },
				textureRect = { x = 2, y = 577, width = 33, height = 58 },
				spriteSourceSize = { width = 33, height = 58 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "spacing_2.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 59 },
				textureRect = { x = 112, y = 178, width = 34, height = 59 },
				spriteSourceSize = { width = 34, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "spacing_3.png",
				spriteColorRect = { x = 0, y = 0, width = 53, height = 59 },
				textureRect = { x = 204, y = 36, width = 53, height = 59 },
				spriteSourceSize = { width = 53, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "spacing_4.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 58 },
				textureRect = { x = 266, y = 50, width = 48, height = 58 },
				spriteSourceSize = { width = 48, height = 58 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "spacing_5.png",
				spriteColorRect = { x = 0, y = 0, width = 5, height = 59 },
				textureRect = { x = 259, y = 36, width = 5, height = 59 },
				spriteSourceSize = { width = 5, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "spacing_6.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 59 },
				textureRect = { x = 263, y = 162, width = 44, height = 59 },
				spriteSourceSize = { width = 44, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "spacing_7.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 59 },
				textureRect = { x = 148, y = 198, width = 47, height = 59 },
				spriteSourceSize = { width = 47, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "strong_1.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 57 },
				textureRect = { x = 460, y = 187, width = 43, height = 57 },
				spriteSourceSize = { width = 43, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "strong_2.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 53 },
				textureRect = { x = 244, y = 671, width = 30, height = 53 },
				spriteSourceSize = { width = 30, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "strong_3.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 46 },
				textureRect = { x = 2, y = 328, width = 38, height = 46 },
				spriteSourceSize = { width = 38, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "strong_4.png",
				spriteColorRect = { x = 0, y = 0, width = 51, height = 47 },
				textureRect = { x = 2, y = 160, width = 51, height = 47 },
				spriteSourceSize = { width = 51, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "strong_5.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 46 },
				textureRect = { x = 266, y = 2, width = 56, height = 46 },
				spriteSourceSize = { width = 56, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "strong_6.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 67 },
				textureRect = { x = 2, y = 209, width = 50, height = 67 },
				spriteSourceSize = { width = 50, height = 67 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "style_1.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 64 },
				textureRect = { x = 202, y = 150, width = 47, height = 64 },
				spriteSourceSize = { width = 47, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "style_2.png",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 53 },
				textureRect = { x = 379, y = 556, width = 28, height = 53 },
				spriteSourceSize = { width = 28, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "style_3.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 56 },
				textureRect = { x = 109, y = 432, width = 37, height = 56 },
				spriteSourceSize = { width = 37, height = 56 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "style_4.png",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 59 },
				textureRect = { x = 2, y = 852, width = 22, height = 59 },
				spriteSourceSize = { width = 22, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "style_5.png",
				spriteColorRect = { x = 0, y = 0, width = 33, height = 37 },
				textureRect = { x = 2, y = 637, width = 33, height = 37 },
				spriteSourceSize = { width = 33, height = 37 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "thin_1.png",
				spriteColorRect = { x = 0, y = 0, width = 29, height = 63 },
				textureRect = { x = 172, y = 734, width = 29, height = 63 },
				spriteSourceSize = { width = 29, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "thin_2.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 68 },
				textureRect = { x = 491, y = 334, width = 19, height = 68 },
				spriteSourceSize = { width = 19, height = 68 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "thin_3.png",
				spriteColorRect = { x = 0, y = 0, width = 10, height = 62 },
				textureRect = { x = 63, y = 52, width = 10, height = 62 },
				spriteSourceSize = { width = 10, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "thin_4.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 50 },
				textureRect = { x = 197, y = 818, width = 26, height = 50 },
				spriteSourceSize = { width = 26, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tilde_1.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 60 },
				textureRect = { x = 75, y = 54, width = 52, height = 60 },
				spriteSourceSize = { width = 52, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tilde_2.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 60 },
				textureRect = { x = 388, y = 432, width = 19, height = 60 },
				spriteSourceSize = { width = 19, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tilde_3.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 60 },
				textureRect = { x = 387, y = 494, width = 20, height = 60 },
				spriteSourceSize = { width = 20, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tilde_4.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 61 },
				textureRect = { x = 61, y = 215, width = 47, height = 61 },
				spriteSourceSize = { width = 47, height = 61 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tilde_5.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 45 },
				textureRect = { x = 309, y = 243, width = 41, height = 45 },
				spriteSourceSize = { width = 41, height = 45 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "title_1.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 61 },
				textureRect = { x = 76, y = 477, width = 31, height = 61 },
				spriteSourceSize = { width = 31, height = 61 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "title_2.png",
				spriteColorRect = { x = 0, y = 0, width = 7, height = 47 },
				textureRect = { x = 100, y = 278, width = 7, height = 47 },
				spriteSourceSize = { width = 7, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "title_3.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 51 },
				textureRect = { x = 129, y = 114, width = 17, height = 51 },
				spriteSourceSize = { width = 17, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "title_4.png",
				spriteColorRect = { x = 0, y = 0, width = 4, height = 63 },
				textureRect = { x = 55, y = 160, width = 4, height = 63 },
				spriteSourceSize = { width = 4, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "title_5.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 37 },
				textureRect = { x = 302, y = 528, width = 37, height = 37 },
				spriteSourceSize = { width = 37, height = 37 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

