-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:583229e82a3bee095db72fc3eff0fa10$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "bracket_1.png",
				spriteColorRect = { x = 0, y = 0, width = 76, height = 98 },
				textureRect = { x = 680, y = 818, width = 76, height = 98 },
				spriteSourceSize = { width = 76, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bracket_2.png",
				spriteColorRect = { x = 0, y = 0, width = 88, height = 98 },
				textureRect = { x = 632, y = 138, width = 88, height = 98 },
				spriteSourceSize = { width = 88, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bracket_3.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 92 },
				textureRect = { x = 684, y = 648, width = 80, height = 92 },
				spriteSourceSize = { width = 80, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bracket_4.png",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 92 },
				textureRect = { x = 704, y = 314, width = 84, height = 92 },
				spriteSourceSize = { width = 84, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bracket_5.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 96 },
				textureRect = { x = 734, y = 2, width = 90, height = 96 },
				spriteSourceSize = { width = 90, height = 96 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bracket_6.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 100 },
				textureRect = { x = 292, y = 800, width = 74, height = 100 },
				spriteSourceSize = { width = 74, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bracket_7.png",
				spriteColorRect = { x = 0, y = 0, width = 94, height = 96 },
				textureRect = { x = 276, y = 390, width = 94, height = 96 },
				spriteSourceSize = { width = 94, height = 96 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bullet_1.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 120 },
				textureRect = { x = 684, y = 526, width = 80, height = 120 },
				spriteSourceSize = { width = 80, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bullet_2.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 80 },
				textureRect = { x = 766, y = 724, width = 80, height = 80 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bullet_3.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 118 },
				textureRect = { x = 96, y = 656, width = 42, height = 118 },
				spriteSourceSize = { width = 42, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bullet_5.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 82 },
				textureRect = { x = 72, y = 1428, width = 64, height = 82 },
				spriteSourceSize = { width = 64, height = 82 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bullet_6.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 98 },
				textureRect = { x = 580, y = 1446, width = 46, height = 98 },
				spriteSourceSize = { width = 46, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "carret_1.png",
				spriteColorRect = { x = 0, y = 0, width = 88, height = 116 },
				textureRect = { x = 734, y = 100, width = 88, height = 116 },
				spriteSourceSize = { width = 88, height = 116 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "carret_2.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 82 },
				textureRect = { x = 848, y = 686, width = 80, height = 82 },
				spriteSourceSize = { width = 80, height = 82 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "carret_3.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 80 },
				textureRect = { x = 132, y = 1558, width = 58, height = 80 },
				spriteSourceSize = { width = 58, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "carret_4.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 82 },
				textureRect = { x = 140, y = 910, width = 74, height = 82 },
				spriteSourceSize = { width = 74, height = 82 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "carret_5.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 102 },
				textureRect = { x = 528, y = 1446, width = 50, height = 102 },
				spriteSourceSize = { width = 50, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cicero_1.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 118 },
				textureRect = { x = 602, y = 626, width = 80, height = 118 },
				spriteSourceSize = { width = 80, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cicero_2.png",
				spriteColorRect = { x = 0, y = 0, width = 12, height = 114 },
				textureRect = { x = 1008, y = 2, width = 12, height = 114 },
				spriteSourceSize = { width = 12, height = 114 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cicero_3.png",
				spriteColorRect = { x = 0, y = 0, width = 70, height = 90 },
				textureRect = { x = 666, y = 918, width = 70, height = 90 },
				spriteSourceSize = { width = 70, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cicero_4.png",
				spriteColorRect = { x = 0, y = 0, width = 70, height = 90 },
				textureRect = { x = 2, y = 1246, width = 70, height = 90 },
				spriteSourceSize = { width = 70, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cicero_5.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 90 },
				textureRect = { x = 356, y = 1198, width = 64, height = 90 },
				spriteSourceSize = { width = 64, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cicero_6.png",
				spriteColorRect = { x = 0, y = 0, width = 70, height = 90 },
				textureRect = { x = 140, y = 1202, width = 70, height = 90 },
				spriteSourceSize = { width = 70, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "comma_1.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 104 },
				textureRect = { x = 2, y = 734, width = 90, height = 104 },
				spriteSourceSize = { width = 90, height = 104 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "comma_2.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 64 },
				textureRect = { x = 872, y = 1088, width = 62, height = 64 },
				spriteSourceSize = { width = 62, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "comma_3.png",
				spriteColorRect = { x = 0, y = 0, width = 114, height = 64 },
				textureRect = { x = 402, y = 2, width = 114, height = 64 },
				spriteSourceSize = { width = 114, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "comma_4.png",
				spriteColorRect = { x = 0, y = 0, width = 114, height = 64 },
				textureRect = { x = 286, y = 2, width = 114, height = 64 },
				spriteSourceSize = { width = 114, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "comma_5.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 64 },
				textureRect = { x = 704, y = 1296, width = 56, height = 64 },
				spriteSourceSize = { width = 56, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "concept_1.png",
				spriteColorRect = { x = 0, y = 2, width = 62, height = 102 },
				textureRect = { x = 502, y = 1156, width = 62, height = 102 },
				spriteSourceSize = { width = 62, height = 104 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "concept_2.png",
				spriteColorRect = { x = 0, y = 1, width = 56, height = 72 },
				textureRect = { x = 780, y = 1260, width = 56, height = 72 },
				spriteSourceSize = { width = 56, height = 74 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "concept_3.png",
				spriteColorRect = { x = 0, y = 1, width = 54, height = 72 },
				textureRect = { x = 400, y = 1446, width = 54, height = 72 },
				spriteSourceSize = { width = 54, height = 74 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "concept_4.png",
				spriteColorRect = { x = 1, y = 0, width = 44, height = 74 },
				textureRect = { x = 480, y = 1636, width = 44, height = 74 },
				spriteSourceSize = { width = 46, height = 74 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "concept_5.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 74 },
				textureRect = { x = 472, y = 1432, width = 54, height = 74 },
				spriteSourceSize = { width = 54, height = 74 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "concept_6.png",
				spriteColorRect = { x = 1, y = 0, width = 52, height = 104 },
				textureRect = { x = 192, y = 1590, width = 52, height = 104 },
				spriteSourceSize = { width = 54, height = 104 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "concept_7.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 90 },
				textureRect = { x = 560, y = 738, width = 40, height = 90 },
				spriteSourceSize = { width = 42, height = 90 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "condensed_1.png",
				spriteColorRect = { x = 0, y = 1, width = 50, height = 128 },
				textureRect = { x = 762, y = 1334, width = 50, height = 128 },
				spriteSourceSize = { width = 50, height = 130 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "condensed_2.png",
				spriteColorRect = { x = 1, y = 1, width = 44, height = 96 },
				textureRect = { x = 56, y = 1810, width = 44, height = 96 },
				spriteSourceSize = { width = 46, height = 98 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "condensed_3.png",
				spriteColorRect = { x = 1, y = 1, width = 44, height = 94 },
				textureRect = { x = 2, y = 1930, width = 44, height = 94 },
				spriteSourceSize = { width = 46, height = 96 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "condensed_4.png",
				spriteColorRect = { x = 1, y = 1, width = 44, height = 126 },
				textureRect = { x = 316, y = 1616, width = 44, height = 126 },
				spriteSourceSize = { width = 46, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "condensed_5.png",
				spriteColorRect = { x = 0, y = 1, width = 44, height = 96 },
				textureRect = { x = 114, y = 1742, width = 44, height = 96 },
				spriteSourceSize = { width = 46, height = 98 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "condensed_6.png",
				spriteColorRect = { x = 0, y = 1, width = 44, height = 94 },
				textureRect = { x = 2, y = 1834, width = 44, height = 94 },
				spriteSourceSize = { width = 46, height = 96 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "condensed_7.png",
				spriteColorRect = { x = 1, y = 1, width = 46, height = 96 },
				textureRect = { x = 580, y = 1546, width = 46, height = 96 },
				spriteSourceSize = { width = 48, height = 98 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "condensed_8.png",
				spriteColorRect = { x = 1, y = 1, width = 44, height = 96 },
				textureRect = { x = 178, y = 1696, width = 44, height = 96 },
				spriteSourceSize = { width = 46, height = 98 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "condensed_9.png",
				spriteColorRect = { x = 1, y = 1, width = 44, height = 126 },
				textureRect = { x = 384, y = 1612, width = 44, height = 126 },
				spriteSourceSize = { width = 46, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "dagger_1.png",
				spriteColorRect = { x = 0, y = 0, width = 82, height = 120 },
				textureRect = { x = 790, y = 314, width = 82, height = 120 },
				spriteSourceSize = { width = 82, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dagger_2.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 82 },
				textureRect = { x = 216, y = 894, width = 74, height = 82 },
				spriteSourceSize = { width = 74, height = 82 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dagger_3.png",
				spriteColorRect = { x = 0, y = 0, width = 82, height = 116 },
				textureRect = { x = 686, y = 408, width = 82, height = 116 },
				spriteSourceSize = { width = 82, height = 116 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dagger_4.png",
				spriteColorRect = { x = 0, y = 0, width = 82, height = 116 },
				textureRect = { x = 686, y = 408, width = 82, height = 116 },
				spriteSourceSize = { width = 82, height = 116 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dagger_5.png",
				spriteColorRect = { x = 0, y = 0, width = 68, height = 82 },
				textureRect = { x = 738, y = 1006, width = 68, height = 82 },
				spriteSourceSize = { width = 68, height = 82 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dagger_6.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 80 },
				textureRect = { x = 68, y = 1512, width = 62, height = 80 },
				spriteSourceSize = { width = 62, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "design_1.png",
				spriteColorRect = { x = 0, y = 1, width = 78, height = 104 },
				textureRect = { x = 766, y = 806, width = 78, height = 104 },
				spriteSourceSize = { width = 78, height = 106 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "design_2.png",
				spriteColorRect = { x = 0, y = 1, width = 78, height = 78 },
				textureRect = { x = 312, y = 604, width = 78, height = 78 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "design_3.png",
				spriteColorRect = { x = 0, y = 1, width = 78, height = 78 },
				textureRect = { x = 232, y = 604, width = 78, height = 78 },
				spriteSourceSize = { width = 78, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "design_4.png",
				spriteColorRect = { x = 0, y = 1, width = 52, height = 78 },
				textureRect = { x = 838, y = 1262, width = 52, height = 78 },
				spriteSourceSize = { width = 54, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "design_5.png",
				spriteColorRect = { x = 0, y = 1, width = 78, height = 104 },
				textureRect = { x = 848, y = 770, width = 78, height = 104 },
				spriteSourceSize = { width = 78, height = 106 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "design_6.png",
				spriteColorRect = { x = 1, y = 1, width = 78, height = 78 },
				textureRect = { x = 482, y = 544, width = 78, height = 78 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "digital_1.png",
				spriteColorRect = { x = 0, y = 0, width = 72, height = 110 },
				textureRect = { x = 140, y = 994, width = 72, height = 110 },
				spriteSourceSize = { width = 74, height = 110 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "digital_2.png",
				spriteColorRect = { x = 0, y = 2, width = 36, height = 72 },
				textureRect = { x = 444, y = 688, width = 36, height = 72 },
				spriteSourceSize = { width = 36, height = 74 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "digital_3.png",
				spriteColorRect = { x = 0, y = 0, width = 72, height = 110 },
				textureRect = { x = 216, y = 978, width = 72, height = 110 },
				spriteSourceSize = { width = 72, height = 110 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "digital_4.png",
				spriteColorRect = { x = 0, y = 2, width = 36, height = 72 },
				textureRect = { x = 444, y = 614, width = 36, height = 72 },
				spriteSourceSize = { width = 36, height = 74 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "digital_5.png",
				spriteColorRect = { x = 0, y = 0, width = 72, height = 110 },
				textureRect = { x = 292, y = 902, width = 72, height = 110 },
				spriteSourceSize = { width = 74, height = 110 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "digital_6.png",
				spriteColorRect = { x = 1, y = 2, width = 72, height = 72 },
				textureRect = { x = 518, y = 908, width = 72, height = 72 },
				spriteSourceSize = { width = 74, height = 74 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "digital_7.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 110 },
				textureRect = { x = 564, y = 536, width = 36, height = 110 },
				spriteSourceSize = { width = 36, height = 110 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dynamic_1.png",
				spriteColorRect = { x = 0, y = 0, width = 88, height = 94 },
				textureRect = { x = 812, y = 218, width = 88, height = 94 },
				spriteSourceSize = { width = 88, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dynamic_2.png",
				spriteColorRect = { x = 1, y = 0, width = 90, height = 94 },
				textureRect = { x = 826, y = 2, width = 90, height = 94 },
				spriteSourceSize = { width = 92, height = 94 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "dynamic_3.png",
				spriteColorRect = { x = 0, y = 1, width = 94, height = 94 },
				textureRect = { x = 2, y = 510, width = 94, height = 94 },
				spriteSourceSize = { width = 94, height = 96 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "dynamic_4.png",
				spriteColorRect = { x = 1, y = 0, width = 94, height = 96 },
				textureRect = { x = 140, y = 448, width = 94, height = 96 },
				spriteSourceSize = { width = 96, height = 96 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "dynamic_5.png",
				spriteColorRect = { x = 1, y = 1, width = 144, height = 94 },
				textureRect = { x = 2, y = 2, width = 144, height = 94 },
				spriteSourceSize = { width = 146, height = 96 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "dynamic_6.png",
				spriteColorRect = { x = 0, y = 1, width = 42, height = 94 },
				textureRect = { x = 48, y = 1908, width = 42, height = 94 },
				spriteSourceSize = { width = 44, height = 96 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "dynamic_7.png",
				spriteColorRect = { x = 0, y = 1, width = 88, height = 94 },
				textureRect = { x = 722, y = 218, width = 88, height = 94 },
				spriteSourceSize = { width = 88, height = 96 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "font_1.png",
				spriteColorRect = { x = 0, y = 0, width = 76, height = 122 },
				textureRect = { x = 482, y = 700, width = 76, height = 122 },
				spriteSourceSize = { width = 76, height = 122 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "font_2.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 92 },
				textureRect = { x = 766, y = 630, width = 80, height = 92 },
				spriteSourceSize = { width = 80, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "font_3.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 90 },
				textureRect = { x = 216, y = 802, width = 74, height = 90 },
				spriteSourceSize = { width = 74, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "font_4.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 108 },
				textureRect = { x = 578, y = 1146, width = 62, height = 108 },
				spriteSourceSize = { width = 62, height = 108 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_1.png",
				spriteColorRect = { x = 0, y = 0, width = 88, height = 118 },
				textureRect = { x = 826, y = 98, width = 88, height = 118 },
				spriteSourceSize = { width = 88, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_2.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 88 },
				textureRect = { x = 282, y = 1256, width = 64, height = 88 },
				spriteSourceSize = { width = 64, height = 88 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_3.png",
				spriteColorRect = { x = 0, y = 0, width = 88, height = 88 },
				textureRect = { x = 512, y = 326, width = 88, height = 88 },
				spriteSourceSize = { width = 88, height = 88 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_4.png",
				spriteColorRect = { x = 0, y = 1, width = 96, height = 86 },
				textureRect = { x = 276, y = 186, width = 96, height = 86 },
				spriteSourceSize = { width = 98, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "geometric_5.png",
				spriteColorRect = { x = 1, y = 0, width = 62, height = 88 },
				textureRect = { x = 348, y = 1290, width = 62, height = 88 },
				spriteSourceSize = { width = 64, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "geometric_6.png",
				spriteColorRect = { x = 0, y = 1, width = 64, height = 86 },
				textureRect = { x = 210, y = 1326, width = 64, height = 86 },
				spriteSourceSize = { width = 64, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "geometric_7.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 88 },
				textureRect = { x = 202, y = 1500, width = 58, height = 88 },
				spriteSourceSize = { width = 58, height = 88 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "geometric_8.png",
				spriteColorRect = { x = 1, y = 0, width = 38, height = 88 },
				textureRect = { x = 562, y = 648, width = 38, height = 88 },
				spriteSourceSize = { width = 40, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "geometric_9.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 88 },
				textureRect = { x = 796, y = 1170, width = 60, height = 88 },
				spriteSourceSize = { width = 60, height = 88 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glyph_1.png",
				spriteColorRect = { x = 0, y = 0, width = 70, height = 114 },
				textureRect = { x = 214, y = 1090, width = 70, height = 114 },
				spriteSourceSize = { width = 70, height = 114 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glyph_2.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 120 },
				textureRect = { x = 254, y = 104, width = 20, height = 120 },
				spriteSourceSize = { width = 20, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glyph_3.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 116 },
				textureRect = { x = 216, y = 684, width = 74, height = 116 },
				spriteSourceSize = { width = 74, height = 116 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glyph_4.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 116 },
				textureRect = { x = 664, y = 1010, width = 66, height = 116 },
				spriteSourceSize = { width = 66, height = 116 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glyph_5.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 112 },
				textureRect = { x = 654, y = 1128, width = 62, height = 112 },
				spriteSourceSize = { width = 62, height = 112 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "grapheme_1.png",
				spriteColorRect = { x = 0, y = 1, width = 62, height = 82 },
				textureRect = { x = 138, y = 1474, width = 62, height = 82 },
				spriteSourceSize = { width = 62, height = 84 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "grapheme_2.png",
				spriteColorRect = { x = 1, y = 2, width = 60, height = 84 },
				textureRect = { x = 718, y = 1210, width = 60, height = 84 },
				spriteSourceSize = { width = 62, height = 86 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "grapheme_3.png",
				spriteColorRect = { x = 0, y = 1, width = 62, height = 84 },
				textureRect = { x = 206, y = 1414, width = 62, height = 84 },
				spriteSourceSize = { width = 62, height = 86 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "grapheme_4.png",
				spriteColorRect = { x = 1, y = 1, width = 48, height = 82 },
				textureRect = { x = 456, y = 1508, width = 48, height = 82 },
				spriteSourceSize = { width = 50, height = 84 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "grapheme_5.png",
				spriteColorRect = { x = 0, y = 1, width = 56, height = 82 },
				textureRect = { x = 934, y = 1208, width = 56, height = 82 },
				spriteSourceSize = { width = 58, height = 84 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "grapheme_6.png",
				spriteColorRect = { x = 0, y = 1, width = 60, height = 82 },
				textureRect = { x = 566, y = 1256, width = 60, height = 82 },
				spriteSourceSize = { width = 62, height = 84 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "grapheme_7.png",
				spriteColorRect = { x = 0, y = 1, width = 116, height = 84 },
				textureRect = { x = 2, y = 98, width = 116, height = 84 },
				spriteSourceSize = { width = 118, height = 86 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "grapheme_8.png",
				spriteColorRect = { x = 0, y = 1, width = 60, height = 82 },
				textureRect = { x = 642, y = 1242, width = 60, height = 82 },
				spriteSourceSize = { width = 62, height = 84 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hyphen_1.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 118 },
				textureRect = { x = 936, y = 1088, width = 60, height = 118 },
				spriteSourceSize = { width = 60, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hyphen_2.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 120 },
				textureRect = { x = 2, y = 840, width = 74, height = 120 },
				spriteSourceSize = { width = 74, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hyphen_3.png",
				spriteColorRect = { x = 0, y = 0, width = 76, height = 120 },
				textureRect = { x = 602, y = 746, width = 76, height = 120 },
				spriteSourceSize = { width = 76, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hyphen_4.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 118 },
				textureRect = { x = 732, y = 1090, width = 62, height = 118 },
				spriteSourceSize = { width = 62, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hyphen_5.png",
				spriteColorRect = { x = 0, y = 0, width = 68, height = 90 },
				textureRect = { x = 2, y = 1338, width = 68, height = 90 },
				spriteSourceSize = { width = 68, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hyphen_6.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 88 },
				textureRect = { x = 422, y = 1228, width = 62, height = 88 },
				spriteSourceSize = { width = 62, height = 88 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_1.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 112 },
				textureRect = { x = 490, y = 288, width = 20, height = 112 },
				spriteSourceSize = { width = 20, height = 112 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_2.png",
				spriteColorRect = { x = 0, y = 0, width = 88, height = 92 },
				textureRect = { x = 614, y = 238, width = 88, height = 92 },
				spriteSourceSize = { width = 88, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_3.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 92 },
				textureRect = { x = 372, y = 388, width = 20, height = 92 },
				spriteSourceSize = { width = 20, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_4.png",
				spriteColorRect = { x = 0, y = 0, width = 82, height = 92 },
				textureRect = { x = 770, y = 436, width = 82, height = 92 },
				spriteSourceSize = { width = 82, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_5.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 92 },
				textureRect = { x = 372, y = 294, width = 20, height = 92 },
				spriteSourceSize = { width = 20, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_6.png",
				spriteColorRect = { x = 0, y = 0, width = 88, height = 94 },
				textureRect = { x = 916, y = 136, width = 88, height = 94 },
				spriteSourceSize = { width = 88, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "initial_7.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 92 },
				textureRect = { x = 270, y = 1432, width = 58, height = 92 },
				spriteSourceSize = { width = 58, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "italic_1.png",
				spriteColorRect = { x = 0, y = 0, width = 72, height = 118 },
				textureRect = { x = 444, y = 824, width = 72, height = 118 },
				spriteSourceSize = { width = 72, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "italic_2.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 112 },
				textureRect = { x = 340, y = 1380, width = 58, height = 112 },
				spriteSourceSize = { width = 58, height = 112 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "italic_3.png",
				spriteColorRect = { x = 0, y = 0, width = 82, height = 92 },
				textureRect = { x = 874, y = 406, width = 82, height = 92 },
				spriteSourceSize = { width = 82, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "italic_4.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 118 },
				textureRect = { x = 808, y = 1050, width = 62, height = 118 },
				spriteSourceSize = { width = 62, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "italic_5.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 116 },
				textureRect = { x = 240, y = 226, width = 34, height = 116 },
				spriteSourceSize = { width = 34, height = 116 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "italic_6.png",
				spriteColorRect = { x = 0, y = 0, width = 82, height = 90 },
				textureRect = { x = 938, y = 528, width = 82, height = 90 },
				spriteSourceSize = { width = 82, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mark_1.png",
				spriteColorRect = { x = 1, y = 1, width = 114, height = 120 },
				textureRect = { x = 2, y = 184, width = 114, height = 120 },
				spriteSourceSize = { width = 116, height = 122 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mark_2.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 114 },
				textureRect = { x = 292, y = 684, width = 74, height = 114 },
				spriteSourceSize = { width = 74, height = 114 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mark_3.png",
				spriteColorRect = { x = 1, y = 1, width = 72, height = 120 },
				textureRect = { x = 2, y = 1038, width = 72, height = 120 },
				spriteSourceSize = { width = 74, height = 122 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mark_4.png",
				spriteColorRect = { x = 0, y = 1, width = 68, height = 120 },
				textureRect = { x = 286, y = 1134, width = 68, height = 120 },
				spriteSourceSize = { width = 70, height = 122 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "micro_1.png",
				spriteColorRect = { x = 1, y = 1, width = 106, height = 108 },
				textureRect = { x = 394, y = 68, width = 106, height = 108 },
				spriteSourceSize = { width = 108, height = 110 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "micro_2.png",
				spriteColorRect = { x = 0, y = 0, width = 2, height = 96 },
				textureRect = { x = 140, y = 224, width = 2, height = 96 },
				spriteSourceSize = { width = 4, height = 96 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "micro_3.png",
				spriteColorRect = { x = 0, y = 0, width = 94, height = 102 },
				textureRect = { x = 140, y = 344, width = 94, height = 102 },
				spriteSourceSize = { width = 96, height = 102 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "micro_4.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 96 },
				textureRect = { x = 74, y = 1330, width = 64, height = 96 },
				spriteSourceSize = { width = 64, height = 96 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "micro_5.png",
				spriteColorRect = { x = 1, y = 0, width = 100, height = 102 },
				textureRect = { x = 518, y = 96, width = 100, height = 102 },
				spriteSourceSize = { width = 102, height = 102 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mono_1.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 100 },
				textureRect = { x = 148, y = 2, width = 136, height = 100 },
				spriteSourceSize = { width = 138, height = 100 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mono_2.png",
				spriteColorRect = { x = 0, y = 1, width = 80, height = 74 },
				textureRect = { x = 684, y = 742, width = 80, height = 74 },
				spriteSourceSize = { width = 80, height = 76 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mono_3.png",
				spriteColorRect = { x = 1, y = 1, width = 86, height = 74 },
				textureRect = { x = 902, y = 232, width = 86, height = 74 },
				spriteSourceSize = { width = 88, height = 76 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mono_4.png",
				spriteColorRect = { x = 1, y = 1, width = 78, height = 74 },
				textureRect = { x = 482, y = 624, width = 78, height = 74 },
				spriteSourceSize = { width = 80, height = 76 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "page_1.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 126 },
				textureRect = { x = 482, y = 416, width = 80, height = 126 },
				spriteSourceSize = { width = 80, height = 126 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "page_2.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 92 },
				textureRect = { x = 848, y = 592, width = 80, height = 92 },
				spriteSourceSize = { width = 80, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "page_3.png",
				spriteColorRect = { x = 0, y = 0, width = 88, height = 132 },
				textureRect = { x = 918, y = 2, width = 88, height = 132 },
				spriteSourceSize = { width = 88, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "page_4.png",
				spriteColorRect = { x = 0, y = 0, width = 68, height = 92 },
				textureRect = { x = 140, y = 1294, width = 68, height = 92 },
				spriteSourceSize = { width = 68, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pica_1.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 88 },
				textureRect = { x = 140, y = 820, width = 74, height = 88 },
				spriteSourceSize = { width = 76, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pica_2.png",
				spriteColorRect = { x = 0, y = 1, width = 32, height = 98 },
				textureRect = { x = 106, y = 434, width = 32, height = 98 },
				spriteSourceSize = { width = 32, height = 100 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pica_3.png",
				spriteColorRect = { x = 0, y = 1, width = 62, height = 70 },
				textureRect = { x = 2, y = 1580, width = 62, height = 70 },
				spriteSourceSize = { width = 64, height = 72 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pica_4.png",
				spriteColorRect = { x = 0, y = 1, width = 64, height = 70 },
				textureRect = { x = 2, y = 1508, width = 64, height = 70 },
				spriteSourceSize = { width = 66, height = 72 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pitch_1.png",
				spriteColorRect = { x = 1, y = 0, width = 70, height = 118 },
				textureRect = { x = 290, y = 1014, width = 70, height = 118 },
				spriteSourceSize = { width = 72, height = 118 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pitch_2.png",
				spriteColorRect = { x = 0, y = 0, width = 70, height = 118 },
				textureRect = { x = 366, y = 992, width = 70, height = 118 },
				spriteSourceSize = { width = 70, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pitch_3.png",
				spriteColorRect = { x = 0, y = 0, width = 70, height = 94 },
				textureRect = { x = 140, y = 1106, width = 70, height = 94 },
				spriteSourceSize = { width = 70, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pitch_4.png",
				spriteColorRect = { x = 0, y = 0, width = 70, height = 84 },
				textureRect = { x = 362, y = 1112, width = 70, height = 84 },
				spriteSourceSize = { width = 72, height = 84 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pitch_5.png",
				spriteColorRect = { x = 0, y = 0, width = 70, height = 118 },
				textureRect = { x = 442, y = 944, width = 70, height = 118 },
				spriteSourceSize = { width = 72, height = 118 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "playful_1.png",
				spriteColorRect = { x = 0, y = 0, width = 104, height = 106 },
				textureRect = { x = 2, y = 306, width = 104, height = 106 },
				spriteSourceSize = { width = 104, height = 106 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playful_2.png",
				spriteColorRect = { x = 0, y = 1, width = 70, height = 86 },
				textureRect = { x = 438, y = 1064, width = 70, height = 86 },
				spriteSourceSize = { width = 72, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "playful_3.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 98 },
				textureRect = { x = 766, y = 530, width = 80, height = 98 },
				spriteSourceSize = { width = 82, height = 98 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "playful_4.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 90 },
				textureRect = { x = 930, y = 620, width = 80, height = 90 },
				spriteSourceSize = { width = 80, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playful_5.png",
				spriteColorRect = { x = 1, y = 0, width = 62, height = 84 },
				textureRect = { x = 276, y = 1346, width = 62, height = 84 },
				spriteSourceSize = { width = 64, height = 84 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "playful_6.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 92 },
				textureRect = { x = 846, y = 876, width = 78, height = 92 },
				spriteSourceSize = { width = 78, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playful_7.png",
				spriteColorRect = { x = 0, y = 1, width = 70, height = 86 },
				textureRect = { x = 514, y = 982, width = 70, height = 86 },
				spriteSourceSize = { width = 70, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "point_1.png",
				spriteColorRect = { x = 0, y = 0, width = 96, height = 124 },
				textureRect = { x = 516, y = 200, width = 96, height = 124 },
				spriteSourceSize = { width = 96, height = 124 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "point_2.png",
				spriteColorRect = { x = 0, y = 0, width = 96, height = 100 },
				textureRect = { x = 394, y = 178, width = 96, height = 100 },
				spriteSourceSize = { width = 96, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "point_3.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 124 },
				textureRect = { x = 120, y = 98, width = 26, height = 124 },
				spriteSourceSize = { width = 26, height = 124 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "point_4.png",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 96 },
				textureRect = { x = 902, y = 308, width = 84, height = 96 },
				spriteSourceSize = { width = 84, height = 96 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "point_5.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 120 },
				textureRect = { x = 330, y = 1494, width = 52, height = 120 },
				spriteSourceSize = { width = 52, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_1.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 102 },
				textureRect = { x = 928, y = 818, width = 78, height = 102 },
				spriteSourceSize = { width = 78, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_2.png",
				spriteColorRect = { x = 0, y = 0, width = 72, height = 76 },
				textureRect = { x = 592, y = 868, width = 72, height = 76 },
				spriteSourceSize = { width = 72, height = 76 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_3.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 100 },
				textureRect = { x = 368, y = 776, width = 74, height = 100 },
				spriteSourceSize = { width = 74, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_4.png",
				spriteColorRect = { x = 0, y = 0, width = 72, height = 76 },
				textureRect = { x = 518, y = 830, width = 72, height = 76 },
				spriteSourceSize = { width = 72, height = 76 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_5.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 106 },
				textureRect = { x = 374, y = 186, width = 18, height = 106 },
				spriteSourceSize = { width = 18, height = 106 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_6.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 76 },
				textureRect = { x = 2, y = 1430, width = 64, height = 76 },
				spriteSourceSize = { width = 64, height = 76 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "regular_7.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 76 },
				textureRect = { x = 432, y = 1592, width = 46, height = 76 },
				spriteSourceSize = { width = 46, height = 76 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rubric_1.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 120 },
				textureRect = { x = 684, y = 1362, width = 50, height = 120 },
				spriteSourceSize = { width = 50, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rubric_2.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 88 },
				textureRect = { x = 60, y = 1720, width = 52, height = 88 },
				spriteSourceSize = { width = 52, height = 88 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rubric_3.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 128 },
				textureRect = { x = 628, y = 1326, width = 54, height = 128 },
				spriteSourceSize = { width = 54, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rubric_4.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 88 },
				textureRect = { x = 444, y = 524, width = 36, height = 88 },
				spriteSourceSize = { width = 36, height = 88 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rubric_5.png",
				spriteColorRect = { x = 0, y = 0, width = 12, height = 122 },
				textureRect = { x = 502, y = 164, width = 12, height = 122 },
				spriteSourceSize = { width = 12, height = 122 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rubric_6.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 90 },
				textureRect = { x = 384, y = 1520, width = 46, height = 90 },
				spriteSourceSize = { width = 46, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sans_1.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 104 },
				textureRect = { x = 930, y = 712, width = 78, height = 104 },
				spriteSourceSize = { width = 78, height = 104 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sans_2.png",
				spriteColorRect = { x = 1, y = 0, width = 76, height = 78 },
				textureRect = { x = 914, y = 1008, width = 76, height = 78 },
				spriteSourceSize = { width = 78, height = 78 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sans_3.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 78 },
				textureRect = { x = 364, y = 524, width = 78, height = 78 },
				spriteSourceSize = { width = 78, height = 78 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sans_4.png",
				spriteColorRect = { x = 1, y = 0, width = 76, height = 78 },
				textureRect = { x = 836, y = 970, width = 76, height = 78 },
				spriteSourceSize = { width = 78, height = 78 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sketch_1.png",
				spriteColorRect = { x = 0, y = 0, width = 82, height = 170 },
				textureRect = { x = 602, y = 332, width = 82, height = 170 },
				spriteSourceSize = { width = 82, height = 170 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sketch_2.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 170 },
				textureRect = { x = 486, y = 1260, width = 58, height = 170 },
				spriteSourceSize = { width = 58, height = 170 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sketch_3.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 70 },
				textureRect = { x = 526, y = 1636, width = 44, height = 70 },
				spriteSourceSize = { width = 44, height = 70 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sketch_4.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 170 },
				textureRect = { x = 392, y = 604, width = 50, height = 170 },
				spriteSourceSize = { width = 50, height = 170 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sketch_5.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 70 },
				textureRect = { x = 430, y = 1670, width = 44, height = 70 },
				spriteSourceSize = { width = 44, height = 70 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sketch_6.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 170 },
				textureRect = { x = 78, y = 914, width = 60, height = 170 },
				spriteSourceSize = { width = 60, height = 170 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slab_1.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 116 },
				textureRect = { x = 628, y = 1456, width = 48, height = 116 },
				spriteSourceSize = { width = 48, height = 116 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slab_2.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 118 },
				textureRect = { x = 564, y = 416, width = 36, height = 118 },
				spriteSourceSize = { width = 36, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slab_3.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 94 },
				textureRect = { x = 2, y = 1652, width = 56, height = 94 },
				spriteSourceSize = { width = 56, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slab_4.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 124 },
				textureRect = { x = 66, y = 1594, width = 56, height = 124 },
				spriteSourceSize = { width = 56, height = 124 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slash_1.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 134 },
				textureRect = { x = 140, y = 684, width = 74, height = 134 },
				spriteSourceSize = { width = 74, height = 134 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slash_2.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 136 },
				textureRect = { x = 94, y = 776, width = 44, height = 136 },
				spriteSourceSize = { width = 44, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slash_3.png",
				spriteColorRect = { x = 0, y = 0, width = 72, height = 84 },
				textureRect = { x = 2, y = 1160, width = 72, height = 84 },
				spriteSourceSize = { width = 72, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slash_4.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 84 },
				textureRect = { x = 2, y = 1748, width = 52, height = 84 },
				spriteSourceSize = { width = 52, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slash_5.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 136 },
				textureRect = { x = 140, y = 546, width = 90, height = 136 },
				spriteSourceSize = { width = 90, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sort_1.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 118 },
				textureRect = { x = 76, y = 1210, width = 62, height = 118 },
				spriteSourceSize = { width = 62, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sort_2.png",
				spriteColorRect = { x = 0, y = 0, width = 70, height = 86 },
				textureRect = { x = 592, y = 946, width = 70, height = 86 },
				spriteSourceSize = { width = 70, height = 86 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sort_3.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 84 },
				textureRect = { x = 506, y = 1550, width = 46, height = 84 },
				spriteSourceSize = { width = 46, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sort_4.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 106 },
				textureRect = { x = 262, y = 1526, width = 52, height = 106 },
				spriteSourceSize = { width = 52, height = 106 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "space_1.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 110 },
				textureRect = { x = 586, y = 1034, width = 66, height = 110 },
				spriteSourceSize = { width = 66, height = 110 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "space_2.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 120 },
				textureRect = { x = 602, y = 504, width = 80, height = 120 },
				spriteSourceSize = { width = 80, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "space_3.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 84 },
				textureRect = { x = 926, y = 922, width = 78, height = 84 },
				spriteSourceSize = { width = 78, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "space_4.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 84 },
				textureRect = { x = 140, y = 1388, width = 64, height = 84 },
				spriteSourceSize = { width = 64, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "space_5.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 84 },
				textureRect = { x = 510, y = 1070, width = 66, height = 84 },
				spriteSourceSize = { width = 66, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "spacing_1.png",
				spriteColorRect = { x = 0, y = 1, width = 64, height = 114 },
				textureRect = { x = 958, y = 412, width = 64, height = 114 },
				spriteSourceSize = { width = 66, height = 116 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spacing_2.png",
				spriteColorRect = { x = 0, y = 0, width = 68, height = 118 },
				textureRect = { x = 212, y = 1206, width = 68, height = 118 },
				spriteSourceSize = { width = 68, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "spacing_3.png",
				spriteColorRect = { x = 0, y = 1, width = 106, height = 116 },
				textureRect = { x = 286, y = 68, width = 106, height = 116 },
				spriteSourceSize = { width = 106, height = 118 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spacing_4.png",
				spriteColorRect = { x = 0, y = 2, width = 94, height = 114 },
				textureRect = { x = 276, y = 274, width = 94, height = 114 },
				spriteSourceSize = { width = 96, height = 116 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spacing_5.png",
				spriteColorRect = { x = 0, y = 2, width = 10, height = 116 },
				textureRect = { x = 620, y = 96, width = 10, height = 116 },
				spriteSourceSize = { width = 10, height = 118 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spacing_6.png",
				spriteColorRect = { x = 1, y = 0, width = 86, height = 118 },
				textureRect = { x = 394, y = 404, width = 86, height = 118 },
				spriteSourceSize = { width = 88, height = 118 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spacing_7.png",
				spriteColorRect = { x = 0, y = 1, width = 94, height = 116 },
				textureRect = { x = 144, y = 226, width = 94, height = 116 },
				spriteSourceSize = { width = 94, height = 118 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "strong_1.png",
				spriteColorRect = { x = 0, y = 0, width = 86, height = 114 },
				textureRect = { x = 276, y = 488, width = 86, height = 114 },
				spriteSourceSize = { width = 86, height = 114 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "strong_2.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 106 },
				textureRect = { x = 872, y = 1154, width = 60, height = 106 },
				spriteSourceSize = { width = 60, height = 106 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "strong_3.png",
				spriteColorRect = { x = 0, y = 0, width = 76, height = 92 },
				textureRect = { x = 758, y = 912, width = 76, height = 92 },
				spriteSourceSize = { width = 76, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "strong_4.png",
				spriteColorRect = { x = 0, y = 0, width = 102, height = 94 },
				textureRect = { x = 2, y = 414, width = 102, height = 94 },
				spriteSourceSize = { width = 102, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "strong_5.png",
				spriteColorRect = { x = 0, y = 0, width = 112, height = 92 },
				textureRect = { x = 518, y = 2, width = 112, height = 92 },
				spriteSourceSize = { width = 112, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "strong_6.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 134 },
				textureRect = { x = 632, y = 2, width = 100, height = 134 },
				spriteSourceSize = { width = 100, height = 134 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "style_1.png",
				spriteColorRect = { x = 1, y = 1, width = 92, height = 126 },
				textureRect = { x = 2, y = 606, width = 92, height = 126 },
				spriteSourceSize = { width = 94, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "style_2.png",
				spriteColorRect = { x = 0, y = 2, width = 54, height = 104 },
				textureRect = { x = 546, y = 1340, width = 54, height = 104 },
				spriteSourceSize = { width = 56, height = 106 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "style_3.png",
				spriteColorRect = { x = 1, y = 0, width = 72, height = 112 },
				textureRect = { x = 368, y = 878, width = 72, height = 112 },
				spriteSourceSize = { width = 74, height = 112 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "style_4.png",
				spriteColorRect = { x = 0, y = 1, width = 44, height = 116 },
				textureRect = { x = 246, y = 1634, width = 44, height = 116 },
				spriteSourceSize = { width = 44, height = 118 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "style_5.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 74 },
				textureRect = { x = 434, y = 1152, width = 66, height = 74 },
				spriteSourceSize = { width = 66, height = 74 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "thin_1.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 126 },
				textureRect = { x = 412, y = 1318, width = 58, height = 126 },
				spriteSourceSize = { width = 58, height = 126 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "thin_2.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 136 },
				textureRect = { x = 236, y = 344, width = 38, height = 136 },
				spriteSourceSize = { width = 38, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "thin_3.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 124 },
				textureRect = { x = 118, y = 224, width = 20, height = 124 },
				spriteSourceSize = { width = 20, height = 124 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "thin_4.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 100 },
				textureRect = { x = 124, y = 1640, width = 52, height = 100 },
				spriteSourceSize = { width = 52, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tilde_1.png",
				spriteColorRect = { x = 0, y = 0, width = 104, height = 120 },
				textureRect = { x = 148, y = 104, width = 104, height = 120 },
				spriteSourceSize = { width = 104, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tilde_2.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 120 },
				textureRect = { x = 236, y = 482, width = 38, height = 120 },
				spriteSourceSize = { width = 38, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tilde_3.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 120 },
				textureRect = { x = 98, y = 534, width = 40, height = 120 },
				spriteSourceSize = { width = 40, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tilde_4.png",
				spriteColorRect = { x = 0, y = 0, width = 94, height = 122 },
				textureRect = { x = 394, y = 280, width = 94, height = 122 },
				spriteSourceSize = { width = 94, height = 122 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tilde_5.png",
				spriteColorRect = { x = 0, y = 0, width = 82, height = 90 },
				textureRect = { x = 854, y = 500, width = 82, height = 90 },
				spriteSourceSize = { width = 82, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "title_1.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 122 },
				textureRect = { x = 76, y = 1086, width = 62, height = 122 },
				spriteSourceSize = { width = 62, height = 122 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "title_2.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 94 },
				textureRect = { x = 502, y = 68, width = 14, height = 94 },
				spriteSourceSize = { width = 14, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "title_3.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 102 },
				textureRect = { x = 988, y = 308, width = 34, height = 102 },
				spriteSourceSize = { width = 34, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "title_4.png",
				spriteColorRect = { x = 0, y = 0, width = 8, height = 126 },
				textureRect = { x = 108, y = 306, width = 8, height = 126 },
				spriteSourceSize = { width = 8, height = 126 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "title_5.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 74 },
				textureRect = { x = 2, y = 962, width = 74, height = 74 },
				spriteSourceSize = { width = 74, height = 74 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

